import './globals.css'
import { Inter, Encode_Sans,} from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const encodeSans = Encode_Sans({ subsets: ["latin"]})

export const metadata = {
  title: 'Rodrigo Lezama - Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={encodeSans.className}>{children}</body>
    </html>
  )
}
