import "./globals.css";
import { Encode_Sans } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Providers from "../providers";

const encodeSans = Encode_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Rodrigo Lezama - Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={encodeSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
